# Kubernetes Resources Schema
# Feature: 018-home-assistant
# Scope: Phase 1 - Base Installation + Prometheus Integration
# Purpose: K8s manifests for Home Assistant deployment

---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: homelab

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate  # PVC can only be mounted by one pod
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          securityContext:
            privileged: false
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
  selector:
    app.kubernetes.io/name: home-assistant

---
# Ingress for local domain (local-ca certificate)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-local
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: local-ca
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  ingressClassName: traefik
  rules:
    - host: homeassistant.chocolandiadc.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
  tls:
    - hosts:
        - homeassistant.chocolandiadc.local
      secretName: home-assistant-local-tls

---
# Ingress for external domain (Let's Encrypt certificate)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-external
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  ingressClassName: traefik
  rules:
    - host: homeassistant.chocolandiadc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
  tls:
    - hosts:
        - homeassistant.chocolandiadc.com
      secretName: home-assistant-external-tls

# NOTE: Secret for Govee API key removed - deferred to Phase 2
# User will configure Govee integration manually via HACS or Alexa
