---
# SSL/TLS Certificates for chocolandiadc.com services
# Managed by cert-manager with Let's Encrypt production issuer

---
# Certificate for Pi-hole Web Admin
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-tls
  namespace: default
spec:
  secretName: pihole-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: pihole.chocolandiadc.com
  dnsNames:
    - pihole.chocolandiadc.com
  renewBefore: 720h  # 30 days before expiry
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always

---
# Certificate for Grafana
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: grafana.chocolandiadc.com
  dnsNames:
    - grafana.chocolandiadc.com
  renewBefore: 720h  # 30 days before expiry
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always

---
# Certificate for Traefik Dashboard
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-tls
  namespace: traefik
spec:
  secretName: traefik-dashboard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: traefik.chocolandiadc.com
  dnsNames:
    - traefik.chocolandiadc.com
  renewBefore: 720h  # 30 days before expiry
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
