#!/usr/bin/env bash
#
# generate-homepage.sh - Generate GitHub Wiki homepage (Home.md)
#
# Usage: ./generate-homepage.sh [specs-directory]
# Output: Homepage markdown content to stdout
#

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source utilities
source "${SCRIPT_DIR}/lib/utils.sh"
source "${SCRIPT_DIR}/lib/extract-metadata.sh"

# Configuration
SPECS_DIR="${1:-specs}"
REPO_OWNER="${REPO_OWNER:-cbenitezpy-ueno}"
REPO_NAME="${REPO_NAME:-chocolandia_kube}"

# Show usage
show_usage() {
    cat <<EOF
Usage: $(basename "$0") [specs-directory]

Generate GitHub Wiki homepage (Home.md) with feature index.

Arguments:
  specs-directory   Path to specs directory (default: specs)

Environment Variables:
  REPO_OWNER        GitHub repository owner (default: cbenitezpy-ueno)
  REPO_NAME         GitHub repository name (default: chocolandia_kube)

Example:
  ./$(basename "$0") specs > Home.md

EOF
}

# Handle help flag
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    show_usage
    exit 0
fi

# Generate homepage header
generate_header() {
    cat <<'EOF'
# Chocolandia Kube Documentation

Welcome to the chocolandia_kube homelab documentation! This Wiki provides comprehensive guides for all infrastructure features.

## Features

EOF
}

# Generate feature table
generate_feature_table() {
    local specs_dir="$1"

    # Table header
    echo "| # | Feature | Status | Description | Quick Start |"
    echo "|---|---------|--------|-------------|-------------|"

    # Find all feature directories and generate rows
    while IFS= read -r feature_dir; do
        if [[ -z "$feature_dir" ]]; then
            continue
        fi

        # Extract metadata
        local number
        local name
        local title_name
        local status
        local description
        local has_qs
        local wiki_filename

        number=$(extract_feature_number "$feature_dir")
        name=$(extract_feature_name "$feature_dir")
        title_name=$(kebab_to_title_case "$name")
        status=$(get_feature_status "$feature_dir")
        description=$(extract_feature_description "${feature_dir}/spec.md")
        has_qs=$(has_quickstart "$feature_dir")
        wiki_filename=$(generate_wiki_page_filename "$feature_dir")

        # Generate quickstart link or dash
        local quickstart_link
        if [[ "$has_qs" == "true" ]]; then
            quickstart_link="[Quick Start](${wiki_filename}#quick-start)"
        else
            quickstart_link="—"
        fi

        # Generate table row
        echo "| ${number} | [${title_name}](${wiki_filename}) | ${status} | ${description} | ${quickstart_link} |"

    done < <(find_feature_directories "$specs_dir")
}

# Generate documentation types section
generate_documentation_types() {
    cat <<'EOF'

## Documentation Types

Each feature includes:

- **Quick Start**: Step-by-step deployment guide for getting the feature running quickly
- **Specification**: User scenarios, functional requirements, and success criteria (what users need)
- **Implementation Plan**: Technical context, architecture decisions, and constitution compliance check
- **Data Model**: Entities, relationships, and state transitions for features involving data
- **Research**: Technology decisions, alternatives considered, and rationale
- **Tasks**: Detailed implementation task breakdown with priorities and dependencies

EOF
}

# Generate contributing section
generate_contributing() {
    local repo_owner="$1"
    local repo_name="$2"

    cat <<EOF
## Contributing

Documentation is maintained in the [${repo_name} repository](https://github.com/${repo_owner}/${repo_name}).

To update documentation:
1. Edit files in \`specs/XXX-feature-name/\` directory
2. Run \`./scripts/wiki/sync-to-wiki.sh\` to sync to Wiki
3. Or wait for automated sync (runs on every merge to main - future enhancement)

**Do not edit Wiki pages directly** - changes will be overwritten on next sync.

EOF
}

# Generate footer
generate_footer() {
    local repo_owner="$1"
    local repo_name="$2"
    local timestamp

    timestamp=$(get_timestamp)

    cat <<EOF
---

*Last updated: ${timestamp} | Generated by [sync-to-wiki.sh](https://github.com/${repo_owner}/${repo_name}/blob/main/scripts/wiki/sync-to-wiki.sh)*
EOF
}

# Main generation function
main() {
    if [[ ! -d "$SPECS_DIR" ]]; then
        log_error "Specs directory not found: $SPECS_DIR"
        exit 1
    fi

    # Generate all sections
    generate_header
    generate_feature_table "$SPECS_DIR"
    generate_documentation_types
    generate_contributing "$REPO_OWNER" "$REPO_NAME"
    generate_footer "$REPO_OWNER" "$REPO_NAME"
}

# Run main if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
