#!/usr/bin/env bash
#
# sync-to-wiki.sh - Main orchestration script to sync documentation to GitHub Wiki
#
# Usage: ./sync-to-wiki.sh [--dry-run]
#

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source utilities
source "${SCRIPT_DIR}/lib/utils.sh"

# Configuration
REPO_OWNER="${REPO_OWNER:-cbenitezpy-ueno}"
REPO_NAME="${REPO_NAME:-chocolandia_kube}"
WIKI_REPO_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}.wiki.git"
WIKI_TEMP_DIR="/tmp/${REPO_NAME}.wiki"
SPECS_DIR="${SPECS_DIR:-specs}"
DRY_RUN=false
WITH_SIDEBAR=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --with-sidebar)
            WITH_SIDEBAR=true
            shift
            ;;
        -h|--help)
            cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Sync all documentation from repository to GitHub Wiki.

Options:
  --dry-run       Generate pages without pushing to Wiki (validation only)
  --with-sidebar  Generate sidebar navigation (_Sidebar.md) (optional)
  -h, --help      Show this help message

Environment Variables:
  REPO_OWNER   GitHub repository owner (default: cbenitezpy-ueno)
  REPO_NAME    GitHub repository name (default: chocolandia_kube)
  SPECS_DIR    Path to specs directory (default: specs)

Examples:
  # Normal sync (push to Wiki)
  ./$(basename "$0")

  # Sync with sidebar navigation
  ./$(basename "$0") --with-sidebar

  # Dry run (generate without pushing)
  ./$(basename "$0") --dry-run

EOF
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Verify required commands
verify_commands git || exit 1

# Clean up function
cleanup() {
    if [[ -d "$WIKI_TEMP_DIR" ]] && [[ "$DRY_RUN" == false ]]; then
        log_info "Cleaning up temporary Wiki directory..."
        rm -rf "$WIKI_TEMP_DIR"
    fi
}

# Set trap for cleanup
trap cleanup EXIT

# Clone Wiki repository
clone_wiki_repo() {
    log_info "Cloning Wiki repository..."

    # Remove existing temp directory if it exists
    if [[ -d "$WIKI_TEMP_DIR" ]]; then
        rm -rf "$WIKI_TEMP_DIR"
    fi

    if git clone "$WIKI_REPO_URL" "$WIKI_TEMP_DIR" 2>&1 >/dev/null; then
        log_success "Wiki repository cloned to $WIKI_TEMP_DIR"
        return 0
    else
        log_error "Failed to clone Wiki repository"
        log_error "Make sure GitHub Wiki is initialized at: https://github.com/${REPO_OWNER}/${REPO_NAME}/wiki"
        return 1
    fi
}

# Generate homepage
generate_homepage() {
    log_info "Generating homepage..."

    local homepage_file="${WIKI_TEMP_DIR}/Home.md"

    if "${SCRIPT_DIR}/generate-homepage.sh" "$SPECS_DIR" > "$homepage_file"; then
        log_success "Homepage generated: $homepage_file"
        return 0
    else
        log_error "Failed to generate homepage"
        return 1
    fi
}

# Generate sidebar (optional)
generate_sidebar() {
    log_info "Generating sidebar navigation..."

    local sidebar_file="${WIKI_TEMP_DIR}/_Sidebar.md"

    if "${SCRIPT_DIR}/generate-sidebar.sh" "$SPECS_DIR" > "$sidebar_file"; then
        log_success "Sidebar generated: $sidebar_file"
        return 0
    else
        log_error "Failed to generate sidebar"
        return 1
    fi
}

# Generate feature pages
generate_feature_pages() {
    log_info "Scanning for features..."

    local feature_count=0
    local error_count=0

    while IFS= read -r feature_dir; do
        if [[ -z "$feature_dir" ]]; then
            continue
        fi

        local wiki_filename
        wiki_filename=$(generate_wiki_page_filename "$feature_dir")
        local wiki_file="${WIKI_TEMP_DIR}/${wiki_filename}.md"

        log_info "Generating ${wiki_filename}..."

        if "${SCRIPT_DIR}/generate-feature-page.sh" "$feature_dir" > "$wiki_file"; then
            ((feature_count++))
        else
            log_error "Failed to generate page for $feature_dir"
            ((error_count++))
        fi
    done < <(find_feature_directories "$SPECS_DIR")

    log_success "Generated $feature_count feature pages"

    if [[ $error_count -gt 0 ]]; then
        log_warning "$error_count features had errors"
        return 1
    fi

    return 0
}

# Check for changes
check_for_changes() {
    cd "$WIKI_TEMP_DIR" || return 1

    # Check if there are any changes
    if git diff --quiet && git diff --cached --quiet; then
        return 1  # No changes
    else
        return 0  # Changes detected
    fi
}

# Commit and push changes
commit_and_push() {
    log_info "Committing changes to Wiki..."

    cd "$WIKI_TEMP_DIR" || return 1

    # Add all changes
    git add .

    # Check if there are changes to commit
    if ! check_for_changes; then
        log_info "No changes detected - Wiki is up to date"
        return 0
    fi

    # Commit changes
    local commit_msg="Sync documentation from repository

Updated: $(get_timestamp)
Generated by: scripts/wiki/sync-to-wiki.sh"

    git commit -m "$commit_msg"

    # Push to Wiki
    if [[ "$DRY_RUN" == false ]]; then
        log_info "Pushing to Wiki repository..."
        if git push origin master; then
            log_success "Wiki synchronized successfully!"
            log_info "View at: https://github.com/${REPO_OWNER}/${REPO_NAME}/wiki"
            return 0
        else
            log_error "Failed to push to Wiki repository"
            return 1
        fi
    else
        log_info "DRY RUN: Would push changes to Wiki"
        log_info "Changes staged:"
        git status --short
        return 0
    fi
}

# Show dry run summary
show_dry_run_summary() {
    log_info "=== DRY RUN SUMMARY ==="
    log_info "Generated files in: $WIKI_TEMP_DIR"
    log_info ""
    log_info "Files created:"
    find "$WIKI_TEMP_DIR" -name "*.md" -type f -exec basename {} \; | sort
    log_info ""
    log_info "To actually sync, run without --dry-run flag"
    log_info "Temporary directory preserved at: $WIKI_TEMP_DIR"
}

# Main sync function
main() {
    log_info "=== GitHub Wiki Sync Starting ==="
    log_info "Repository: ${REPO_OWNER}/${REPO_NAME}"
    log_info "Specs directory: $SPECS_DIR"
    log_info "Dry run: $DRY_RUN"
    log_info "Sidebar: $WITH_SIDEBAR"
    log_info ""

    # Verify specs directory exists
    if [[ ! -d "$SPECS_DIR" ]]; then
        log_error "Specs directory not found: $SPECS_DIR"
        exit 1
    fi

    # Clone Wiki repository
    clone_wiki_repo || exit 1

    # Generate homepage
    generate_homepage || exit 1

    # Generate sidebar (optional)
    if [[ "$WITH_SIDEBAR" == true ]]; then
        generate_sidebar || exit 1
    fi

    # Generate feature pages
    generate_feature_pages || exit 1

    # Commit and push (or show dry run summary)
    if [[ "$DRY_RUN" == true ]]; then
        show_dry_run_summary
    else
        commit_and_push || exit 1
    fi

    log_success "=== Sync Complete ==="
}

# Run main
main
