# Kubernetes Resource Contracts for Govee2MQTT Integration
# Feature: 019-govee2mqtt
# Date: 2025-12-04
#
# This file defines the expected Kubernetes resources that will be created
# by the OpenTofu modules. Use this as a reference for validation.

---
# =============================================================================
# MOSQUITTO MQTT BROKER
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
data:
  mosquitto.conf: |
    # Listener configuration
    listener 1883
    protocol mqtt

    # Authentication (disabled for internal cluster use)
    allow_anonymous true

    # Persistence
    persistence true
    persistence_location /mosquitto/data/

    # Logging
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
spec:
  replicas: 1
  strategy:
    type: Recreate  # PVC can only be mounted by one pod
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
            - name: data
              mountPath: /mosquitto/data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  type: ClusterIP
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    app.kubernetes.io/name: mosquitto

---
# =============================================================================
# GOVEE2MQTT BRIDGE
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: govee-credentials
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: govee2mqtt
type: Opaque
stringData:
  GOVEE_API_KEY: "${GOVEE_API_KEY}"  # Will be replaced by OpenTofu
  # Optional credentials for IoT features:
  # GOVEE_EMAIL: "${GOVEE_EMAIL}"
  # GOVEE_PASSWORD: "${GOVEE_PASSWORD}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: govee2mqtt
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: govee2mqtt
    app.kubernetes.io/component: iot-bridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: govee2mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: govee2mqtt
    spec:
      hostNetwork: true  # REQUIRED for Govee LAN device discovery
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: govee2mqtt
          image: ghcr.io/wez/govee2mqtt:latest
          env:
            - name: GOVEE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: govee-credentials
                  key: GOVEE_API_KEY
            - name: GOVEE_MQTT_HOST
              value: "mosquitto.home-assistant.svc.cluster.local"
            - name: GOVEE_MQTT_PORT
              value: "1883"
            - name: TZ
              value: "America/Asuncion"
            - name: GOVEE_TEMPERATURE_SCALE
              value: "C"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          # Note: No liveness/readiness probes as govee2mqtt doesn't expose HTTP endpoints
      restartPolicy: Always

---
# =============================================================================
# VALIDATION TESTS (kubectl apply --dry-run=client)
# =============================================================================
#
# After deployment, validate with:
#
# 1. Check Mosquitto is running:
#    kubectl get pods -n home-assistant -l app.kubernetes.io/name=mosquitto
#
# 2. Check govee2mqtt is running:
#    kubectl get pods -n home-assistant -l app.kubernetes.io/name=govee2mqtt
#
# 3. Test MQTT connectivity from within cluster:
#    kubectl run mqtt-test --rm -it --image=eclipse-mosquitto:latest --restart=Never -- \
#      mosquitto_sub -h mosquitto.home-assistant.svc.cluster.local -t 'homeassistant/#' -v -C 5
#
# 4. Check govee2mqtt logs for device discovery:
#    kubectl logs -n home-assistant -l app.kubernetes.io/name=govee2mqtt --tail=50
#
# 5. Verify devices in Home Assistant:
#    - Navigate to Settings → Devices & Services → MQTT
#    - Govee devices should appear automatically via MQTT discovery
