# Redis Shared - Local Values

locals {
  # Common labels applied to all resources
  common_labels = {
    "app.kubernetes.io/name"       = "redis"
    "app.kubernetes.io/managed-by" = "opentofu"
    "app.kubernetes.io/part-of"    = "redis-shared"
    "feature"                      = "013-redis-deployment"
  }

  # Service names (generated by Helm chart)
  master_service_name   = "${var.release_name}-master"
  replicas_service_name = "${var.release_name}-replicas"

  # DNS names for internal access
  master_dns   = "${local.master_service_name}.${var.namespace}.svc.cluster.local"
  replicas_dns = "${local.replicas_service_name}.${var.namespace}.svc.cluster.local"
}
